src/Oefeningenreeks3/Models/Band.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Oefeningenreeks3.Models
{
    public class Band
    {
        [Display(Name ="Naam van de band")]
        [Required(ErrorMessage ="Geef een naam op voor de band")]
        [MinLength(3, ErrorMessage = "De naam moet minstens {1} tekens langs zijn"), MaxLength(25)]
        public string Naam { get; set; }

        [Display(Name = "Jaar van oprichting")]
        [Required(ErrorMessage ="Voorzie het jaar van oprichten")]
        [Range(minimum: 1920, maximum: 2017, ErrorMessage ="Het jaar van oprichten moet tussen {1} en {2} liggen")]
        public int Jaar { get; set; }
        public List<BandLid> Leden { get; set; }
    }
}

src/Oefeningenreeks3/Models/BandLid.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Oefeningenreeks3.Models
{
    public enum Geslacht
    {
        Man,
        Vrouw
    }

    public class BandLid
    {
        [Display(Name = "Naam bandlid")]
        [Required(ErrorMessage = "Geef een naam op voor het bandlid")]
        public string Naam { get; set; }

        [Display(Name = "Leeftijd")]
        [Required(ErrorMessage = "Geef de leeftijd op")]
        [Range(minimum: 18, maximum: 90, ErrorMessage = "De leeftijd moet tussen {1} en {2} jaar liggen")]
        public int Leeftijd { get; set; }

        [Display(Name = "Geslacht")]
        public Geslacht Geslacht { get; set; }

        [Display(Name = "Nog in leven?")]
        public bool Levend { get; set; }
    }
}

src/Oefeningenreeks3/Controllers/BandController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Oefeningenreeks3.Models;

namespace Oefeningenreeks3.Controllers
{
    public class BandController : Controller
    {
        private List<Band> bands;
        public BandController()
        {
            bands = BandInitializer.StartUp();
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Lijst()
        {
            return View(bands);
        }

        public IActionResult LijstMetLeden()
        {
            return View(bands);
        }

        [HttpGet]
        public IActionResult Maak(string bandnaam, int bandjaar)
        {
            return View(new Band() { Naam=bandnaam, Jaar=bandjaar });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Maak(Band band)
        {
            if (ModelState.IsValid) {
                bands.Add(new Band() { Naam=band.Naam, Jaar=band.Jaar });
                return View("Lijst", bands);
            }
            return View(band);
        }

        public IActionResult JSLijst()
        {
            return Json(bands);
        }
    }
}

src/Oefeningenreeks3/Controllers/BandLidController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Oefeningenreeks3.Models;
using Oefeningenreeks3;

namespace Oefeningenreeks3.Controllers
{
    public class BandLidController : Controller
    {
        private List<Band> bands;
  
        public BandLidController()
        {
            bands = BandInitializer.StartUp();
        }
    
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Lijst()
        {
            return View(bands);
        }

        [HttpGet]
        public IActionResult Maak(string bandlidnaam, int bandlidjaar, Geslacht geslacht, string bandnaam)
        {
            ViewBag.bandnaam = bandnaam;
            return View(new BandLid()
                    { Naam=bandlidnaam, Leeftijd=bandlidjaar, Geslacht=geslacht}
                );
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Maak(BandLid bandLid, string band)
        {
            if (ModelState.IsValid)
            {
                bands.Add(
                     new Band()
                     {
                         Naam = band,
                         Leden = new List<BandLid>()
                            { new BandLid()
                                { Naam = bandLid.Naam, Geslacht = bandLid.Geslacht, Leeftijd= bandLid.Leeftijd, Levend = true }
                            }
                     });
                return View("Lijst", bands);
            }
            return View(bandLid);
        }

    }
}

src/Oefeningenreeks3/Views/Band/Lijst.cshtml
@model IEnumerable<Oefeningenreeks3.Models.Band>
@using Oefeningenreeks3.Models
<h2>Bands</h2>

<ol>
@foreach(Band band in Model)
{
    <li>@band.Naam (@band.Jaar)</li>
}
</ol>
@Html.ActionLink("Naar lijst met leden", "LijstMetLeden")

src/Oefeningenreeks3/Views/Band/LijstMetLeden.cshtml
@model IEnumerable<Oefeningenreeks3.Models.Band>
@using Oefeningenreeks3.Models
<h2>Bands met hun leden</h2>

<ol>
    @foreach (Band band in Model)
    {
        <li>
            @band.Naam (@band.Jaar)
            <ul>
                @foreach (BandLid bandlid in band.Leden)
                {
                    <li>
                        @bandlid.Naam - @bandlid.Leeftijd @(!bandlid.Levend ? "(+)" : "" ) - @bandlid.Geslacht
                    </li>
                }
            </ul>
        </li>
    }
</ol>

src/Oefeningenreeks3/Views/Band/Maak.cshtml
@model Oefeningenreeks3.Models.Band

<h2>@Model.GetType().Name</h2>

@using (Html.BeginForm(FormMethod.Post))
{
    @Html.ValidationSummary()
    @Html.AntiForgeryToken()

    @Html.LabelFor(m => m.Naam)
    @Html.TextBoxFor(m => m.Naam, "", new { @class = "form-control" })
    @*@Html.ValidationMessageFor(m => m.Naam,"", new { @class = "text-danger" })*@
    <br />
    @Html.LabelFor(m => m.Jaar)
    @Html.TextBoxFor(m => m.Jaar, "", new { @class = "form-control" })
    @*@Html.ValidationMessageFor(m => m.Naam,"", new { @class = "text-danger" })*@
    <br />
    <input type="submit" value="Voeg toe" />
}

@* OF  *@

<form asp-controller="Band" asp-action="Maak">
    <div asp-validation-summary="All" class="text-danger"></div>

    <label asp-for="Naam"></label>
    <input asp-for="Naam" class="form-control" />
    <span asp-validation-for="Naam" class="text-danger"></span>
    <br />
    <label asp-for="Jaar"></label>
    <input asp-for="Jaar" class="form-control" />
    <span asp-validation-for="Jaar" class="text-danger"></span>
    <br />
    <input type="submit" value="Voeg toe" />
</form>

src/Oefeningenreeks3/Views/BandLid/Lijst.cshtml
@model IEnumerable<Oefeningenreeks3.Models.Band>
@using Oefeningenreeks3.Models

<h2>Bandleden</h2>

<ul>
    @foreach (Band band in Model)
    {
        @foreach (BandLid bandlid in band.Leden)
        {
            <li>
                [@band.Naam] @bandlid.Naam - @bandlid.Leeftijd @(!bandlid.Levend ? "(+)" : "" ) - @bandlid.Geslacht
            </li>
        }
    }
</ul>

src/Oefeningenreeks3/Views/BandLid/Maak.cshtml
@model Oefeningenreeks3.Models.BandLid
@using Oefeningenreeks3.Models

<h2>@Model.GetType().Name</h2>

@using (Html.BeginForm(FormMethod.Post))
{
    @Html.ValidationSummary()
    @Html.AntiForgeryToken()

    @Html.LabelFor(m => m.Naam)
    @Html.TextBoxFor(m => m.Naam, "", new { @class = "form-control" })
    @*@Html.ValidationMessageFor(m => m.Naam,"", new { @class = "text-danger" })*@
    <br />
    @Html.LabelFor(m => m.Leeftijd)
    @Html.TextBoxFor(m => m.Leeftijd, "", new { @class = "form-control" })
    @*@Html.ValidationMessageFor(m => m.Leeftijd,"", new { @class = "text-danger" })*@
    <br />
    @Html.LabelFor(m => m.Geslacht)
    @Html.DropDownListFor(m => m.Geslacht, new SelectList(Enum.GetValues(typeof(Geslacht))), "", new { @class = "form-control" })
    <br />
    @Html.Label("Band")
    @Html.TextBox("band", (string)ViewBag.bandnaam, new { @class = "form-control" })
    <br />
    <input type="submit" value="Voeg toe" />

}

@*  OF  *@

<form asp-controller="BandLid" asp-action="Maak">
    <div asp-validation-summary="All" class="text-danger"></div>

    <label asp-for="Naam"></label>
    <input asp-for="Naam" class="form-control" />
    <span asp-validation-for="Naam" class="text-danger"></span>
    <br />
    <label asp-for="Leeftijd"></label>
    <input asp-for="Leeftijd" class="form-control" />
    <span asp-validation-for="Leeftijd" class="text-danger"></span>
    <br />
    <label asp-for="Geslacht"></label>
    <select asp-for="Geslacht" asp-items="new SelectList(Enum.GetValues(typeof(Geslacht)))" class="form-control"></select>
    <br />
    <label for="Band">Band</label>
    <input id="Band" name="band" value="@((string)ViewBag.bandnaam)" class="form-control" />
    <br />
    <input type="submit" value="Voeg toe" />
</form>

src/Oefeningenreeks3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Oefeningenreeks3</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Oefeningenreeks3</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - Oefeningenreeks3</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>